name: Terraform Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_service:
        description: 'Select AWS service'
        required: true
        default: 's3'
        type: choice
        options:
          - 's3'
          - 'vpc'
          - 'ec2_linux'
          - 'ec2_windows'
          - 'mysql'
          - 'lambda'
          - 'k8'
      function:
        description: 'Select function'
        required: true
        default: 'plan'
        type: choice
        options:
          - 'plan'
          - 'apply -auto-approve'
          - 'destroy -auto-approve'
          - 'refresh'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.0
      - name: Terraform Init, Validate, and Execute
        env:
          AWS_SERVICE: ${{ github.event.inputs.aws_service || 's3' }}
          FUNCTION: ${{ github.event.inputs.function || 'plan' }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          case $AWS_SERVICE in
            ec2_linux|ec2_windows|vpc|s3|mysql|lambda|k8)
              echo "Running on $AWS_SERVICE"
              cd env/$AWS_SERVICE
              terraform init -reconfigure
              terraform validate
              terraform $FUNCTION
              ;;
            *)
              echo "Invalid AWS service selected"
              exit 1
              ;;
          esac