name: 'Terraform Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      aws_service:
        description: 'Select AWS service'
        required: true
        default: 's3'
        type: choice
        options:
          - s3
          - vpc
          - ec2_linux
          - ec2_windows
          - mysql
          - lambda
          - k8
      function:
        description: 'Select function'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply -auto-approve
          - destroy -auto-approve
          - refresh

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.3

    - name: Debug Inputs
      run: |
        echo "AWS_SERVICE: ${{ github.event.inputs.aws_service }}"
        echo "FUNCTION: ${{ github.event.inputs.function }}"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false